
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 21 19:37:06 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 24;
  public static final int MAP = 15;
  public static final int PRINTCHAR = 49;
  public static final int LBRACKET = 45;
  public static final int CONST = 5;
  public static final int GEQUAL = 29;
  public static final int LPAREN = 41;
  public static final int SEMI = 39;
  public static final int GREATER = 31;
  public static final int CONTINUE = 7;
  public static final int LESS = 32;
  public static final int MINUS = 20;
  public static final int RPAREN = 42;
  public static final int AND = 36;
  public static final int OR = 37;
  public static final int COMMA = 40;
  public static final int INC = 11;
  public static final int PLUS = 19;
  public static final int MULTIPLY = 21;
  public static final int IF = 9;
  public static final int DOT = 22;
  public static final int FINDANY = 33;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int RBRACKET = 46;
  public static final int EQUAL = 28;
  public static final int TRUE = 17;
  public static final int LAMBDA = 26;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int ISEQUAL = 27;
  public static final int NUMBER = 47;
  public static final int MOD = 25;
  public static final int NEQ = 35;
  public static final int IDENT = 48;
  public static final int BREAK = 6;
  public static final int VOID = 16;
  public static final int COLON = 38;
  public static final int FOREACH = 34;
  public static final int LBRACE = 43;
  public static final int ELSE = 10;
  public static final int LEQUAL = 30;
  public static final int READ = 4;
  public static final int WHILE = 13;
  public static final int RBRACE = 44;
  public static final int PROG = 2;
  public static final int DEC = 12;
  public static final int FALSE = 18;
  public static final int PRINT = 3;
  public static final int FINDANDREPLACE = 23;
}

